- name: John Doe
  facebook: JohnDoe
  twitter: JohnDoe
  snapchat: JohnDoe
  instagram: JohnDoe
  linkedin: JohnDoe
  medium: JohnDoe
  github: JohnDoe
  gitlab: JohnDoe
  google-plus: JohnDoe
  reddit: JohnDoe
  spotify: JohnDoe
